version: "3.9"

services:
  postgres:
    image: postgres:15
    command: postgres -c shared_preload_libraries=pg_stat_statements
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5

  db-inspector:
    build: .
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy

#volumes:
#  pgdata: